# Generated by Django 4.2.1 on 2023-05-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='some string', null=True, upload_to='images/'),
        ),
    ]
